package com.iFox.hh.model;

public class Resources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.name
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resUrl
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    private String resurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.type
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.parentId
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.sort
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.id
     *
     * @return the value of resources.id
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.id
     *
     * @param id the value for resources.id
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.name
     *
     * @return the value of resources.name
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.name
     *
     * @param name the value for resources.name
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resUrl
     *
     * @return the value of resources.resUrl
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public String getResurl() {
        return resurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resUrl
     *
     * @param resurl the value for resources.resUrl
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public void setResurl(String resurl) {
        this.resurl = resurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.type
     *
     * @return the value of resources.type
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.type
     *
     * @param type the value for resources.type
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.parentId
     *
     * @return the value of resources.parentId
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.parentId
     *
     * @param parentid the value for resources.parentId
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.sort
     *
     * @return the value of resources.sort
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.sort
     *
     * @param sort the value for resources.sort
     *
     * @mbggenerated Sat Apr 14 15:21:15 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}